# Generated by Django 4.0.4 on 2022-05-23 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltrack',
            name='is_visible',
            field=models.BooleanField(default=False, verbose_name='Виден?'),
        ),
        migrations.AddField(
            model_name='track',
            name='is_visible',
            field=models.BooleanField(default=False, verbose_name='Виден?'),
        ),
    ]
